<?php

declare(strict_types=1);

use Illuminate\Database\Migrations\Migration;
use Tipoff\Addresses\Models\State;

class AddStates extends Migration
{
    public function up()
    {

        if (class_exists(State::class)) {
            foreach ([
                [
                    'id' => 1,
                    'slug' => 'florida',
                    'title' => 'Florida',
                    'abbreviation' => 'FL',
                    'description' => null,
                    'capital' => 'Tallahassee',
                    'country_id' => 1,
                    'created_at' => '2021-03-03 05:51:45',
                    'updated_at' => '2021-03-03 05:51:45',
                ],
                [
                    'id' => 2,
                    'slug' => 'kentucky',
                    'title' => 'Kentucky',
                    'abbreviation' => 'KY',
                    'description' => null,
                    'capital' => 'Frankfort',
                    'country_id' => 1,
                    'created_at' => '2021-03-03 05:51:45',
                    'updated_at' => '2021-03-03 05:51:45',
                ],
                [
                    'id' => 3,
                    'slug' => 'alabama',
                    'title' => 'Alabama',
                    'abbreviation' => 'AL',
                    'description' => null,
                    'capital' => 'Montgomery',
                    'country_id' => 1,
                    'created_at' => '2021-03-03 05:51:45',
                    'updated_at' => '2021-03-03 05:51:45',
                ],
                [
                    'id' => 4,
                    'slug' => 'alaska',
                    'title' => 'Alaska',
                    'abbreviation' => 'AK',
                    'description' => null,
                    'capital' => 'Juneau',
                    'country_id' => 1,
                    'created_at' => '2021-03-03 05:51:45',
                    'updated_at' => '2021-03-03 05:51:45',
                ],
                [
                    'id' => 5,
                    'slug' => 'arizona',
                    'title' => 'Arizona',
                    'abbreviation' => 'AZ',
                    'description' => null,
                    'capital' => 'Phoenix',
                    'country_id' => 1,
                    'created_at' => '2021-03-03 05:51:45',
                    'updated_at' => '2021-03-03 05:51:45',
                ],
                [
                    'id' => 6,
                    'slug' => 'arkansas',
                    'title' => 'Arkansas',
                    'abbreviation' => 'AR',
                    'description' => null,
                    'capital' => 'Little Rock',
                    'country_id' => 1,
                    'created_at' => '2021-03-03 05:51:45',
                    'updated_at' => '2021-03-03 05:51:45',
                ],
                [
                    'id' => 7,
                    'slug' => 'california',
                    'title' => 'California',
                    'abbreviation' => 'CA',
                    'description' => null,
                    'capital' => 'Sacramento',
                    'country_id' => 1,
                    'created_at' => '2021-03-03 05:51:45',
                    'updated_at' => '2021-03-03 05:51:45',
                ],
                [
                    'id' => 8,
                    'slug' => 'colorado',
                    'title' => 'Colorado',
                    'abbreviation' => 'CO',
                    'description' => null,
                    'capital' => 'Denver',
                    'country_id' => 1,
                    'created_at' => '2021-03-03 05:51:45',
                    'updated_at' => '2021-03-03 05:51:45',
                ],
                [
                    'id' => 9,
                    'slug' => 'connecticut',
                    'title' => 'Connecticut',
                    'abbreviation' => 'CT',
                    'description' => null,
                    'capital' => 'Hartford',
                    'country_id' => 1,
                    'created_at' => '2021-03-03 05:51:45',
                    'updated_at' => '2021-03-03 05:51:45',
                ],
                [
                    'id' => 10,
                    'slug' => 'delaware',
                    'title' => 'Delaware',
                    'abbreviation' => 'DE',
                    'description' => null,
                    'capital' => 'Dover',
                    'country_id' => 1,
                    'created_at' => '2021-03-03 05:51:45',
                    'updated_at' => '2021-03-03 05:51:45',
                ],
                [
                    'id' => 11,
                    'slug' => 'georgia',
                    'title' => 'Georgia',
                    'abbreviation' => 'GA',
                    'description' => null,
                    'capital' => 'Atlanta',
                    'country_id' => 1,
                    'created_at' => '2021-03-03 05:51:45',
                    'updated_at' => '2021-03-03 05:51:45',
                ],
                [
                    'id' => 12,
                    'slug' => 'hawaii',
                    'title' => 'Hawaii',
                    'abbreviation' => 'HI',
                    'description' => null,
                    'capital' => 'Honolulu',
                    'country_id' => 1,
                    'created_at' => '2021-03-03 05:51:45',
                    'updated_at' => '2021-03-03 05:51:45',
                ],
                [
                    'id' => 13,
                    'slug' => 'idaho',
                    'title' => 'Idaho',
                    'abbreviation' => 'ID',
                    'description' => null,
                    'capital' => 'Boise',
                    'country_id' => 1,
                    'created_at' => '2021-03-03 05:51:45',
                    'updated_at' => '2021-03-03 05:51:45',
                ],
                [
                    'id' => 14,
                    'slug' => 'illinois',
                    'title' => 'Illinois',
                    'abbreviation' => 'IL',
                    'description' => null,
                    'capital' => 'Springfield',
                    'country_id' => 1,
                    'created_at' => '2021-03-03 05:51:45',
                    'updated_at' => '2021-03-03 05:51:45',
                ],
                [
                    'id' => 15,
                    'slug' => 'indiana',
                    'title' => 'Indiana',
                    'abbreviation' => 'IN',
                    'description' => null,
                    'capital' => 'Indianapolis',
                    'country_id' => 1,
                    'created_at' => '2021-03-03 05:51:45',
                    'updated_at' => '2021-03-03 05:51:45',
                ],
                [
                    'id' => 16,
                    'slug' => 'iowa',
                    'title' => 'Iowa',
                    'abbreviation' => 'IA',
                    'description' => null,
                    'capital' => 'Des Moines',
                    'country_id' => 1,
                    'created_at' => '2021-03-03 05:51:45',
                    'updated_at' => '2021-03-03 05:51:45',
                ],
                [
                    'id' => 17,
                    'slug' => 'kansas',
                    'title' => 'Kansas',
                    'abbreviation' => 'KS',
                    'description' => null,
                    'capital' => 'Topeka',
                    'country_id' => 1,
                    'created_at' => '2021-03-03 05:51:45',
                    'updated_at' => '2021-03-03 05:51:45',
                ],
                [
                    'id' => 18,
                    'slug' => 'louisiana',
                    'title' => 'Louisiana',
                    'abbreviation' => 'LA',
                    'description' => null,
                    'capital' => 'Baton Rouge',
                    'country_id' => 1,
                    'created_at' => '2021-03-03 05:51:45',
                    'updated_at' => '2021-03-03 05:51:45',
                ],
                [
                    'id' => 19,
                    'slug' => 'maine',
                    'title' => 'Maine',
                    'abbreviation' => 'ME',
                    'description' => null,
                    'capital' => 'Augusta',
                    'country_id' => 1,
                    'created_at' => '2021-03-03 05:51:45',
                    'updated_at' => '2021-03-03 05:51:45',
                ],
                [
                    'id' => 20,
                    'slug' => 'maryland',
                    'title' => 'Maryland',
                    'abbreviation' => 'MD',
                    'description' => null,
                    'capital' => 'Annapolis',
                    'country_id' => 1,
                    'created_at' => '2021-03-03 05:51:45',
                    'updated_at' => '2021-03-03 05:51:45',
                ],
                [
                    'id' => 21,
                    'slug' => 'massachusetts',
                    'title' => 'Massachusetts',
                    'abbreviation' => 'MA',
                    'description' => null,
                    'capital' => 'Boston',
                    'country_id' => 1,
                    'created_at' => '2021-03-03 05:51:45',
                    'updated_at' => '2021-03-03 05:51:45',
                ],
                [
                    'id' => 22,
                    'slug' => 'michigan',
                    'title' => 'Michigan',
                    'abbreviation' => 'MI',
                    'description' => null,
                    'capital' => 'Lansing',
                    'country_id' => 1,
                    'created_at' => '2021-03-03 05:51:45',
                    'updated_at' => '2021-03-03 05:51:45',
                ],
                [
                    'id' => 23,
                    'slug' => 'minnesota',
                    'title' => 'Minnesota',
                    'abbreviation' => 'MN',
                    'description' => null,
                    'capital' => 'Saint Paul',
                    'country_id' => 1,
                    'created_at' => '2021-03-03 05:51:45',
                    'updated_at' => '2021-03-03 05:51:45',
                ],
                [
                    'id' => 24,
                    'slug' => 'mississippi',
                    'title' => 'Mississippi',
                    'abbreviation' => 'MS',
                    'description' => null,
                    'capital' => 'Jackson',
                    'country_id' => 1,
                    'created_at' => '2021-03-03 05:51:45',
                    'updated_at' => '2021-03-03 05:51:45',
                ],
                [
                    'id' => 25,
                    'slug' => 'missouri',
                    'title' => 'Missouri',
                    'abbreviation' => 'MO',
                    'description' => null,
                    'capital' => 'Jefferson City',
                    'country_id' => 1,
                    'created_at' => '2021-03-03 05:51:45',
                    'updated_at' => '2021-03-03 05:51:45',
                ],
                [
                    'id' => 26,
                    'slug' => 'montana',
                    'title' => 'Montana',
                    'abbreviation' => 'MT',
                    'description' => null,
                    'capital' => 'Helena',
                    'country_id' => 1,
                    'created_at' => '2021-03-03 05:51:45',
                    'updated_at' => '2021-03-03 05:51:45',
                ],
                [
                    'id' => 27,
                    'slug' => 'nebraska',
                    'title' => 'Nebraska',
                    'abbreviation' => 'NE',
                    'description' => null,
                    'capital' => 'Lincoln',
                    'country_id' => 1,
                    'created_at' => '2021-03-03 05:51:45',
                    'updated_at' => '2021-03-03 05:51:45',
                ],
                [
                    'id' => 28,
                    'slug' => 'nevada',
                    'title' => 'Nevada',
                    'abbreviation' => 'NV',
                    'description' => null,
                    'capital' => 'Carson City',
                    'country_id' => 1,
                    'created_at' => '2021-03-03 05:51:45',
                    'updated_at' => '2021-03-03 05:51:45',
                ],
                [
                    'id' => 29,
                    'slug' => 'new-hampshire',
                    'title' => 'New Hampshire',
                    'abbreviation' => 'NH',
                    'description' => null,
                    'capital' => 'Concord',
                    'country_id' => 1,
                    'created_at' => '2021-03-03 05:51:45',
                    'updated_at' => '2021-03-03 05:51:45',
                ],
                [
                    'id' => 30,
                    'slug' => 'new-jersey',
                    'title' => 'New Jersey',
                    'abbreviation' => 'NJ',
                    'description' => null,
                    'capital' => 'Trenton',
                    'country_id' => 1,
                    'created_at' => '2021-03-03 05:51:45',
                    'updated_at' => '2021-03-03 05:51:45',
                ],
                [
                    'id' => 31,
                    'slug' => 'new-mexico',
                    'title' => 'New Mexico',
                    'abbreviation' => 'NM',
                    'description' => null,
                    'capital' => 'Santa Fe',
                    'country_id' => 1,
                    'created_at' => '2021-03-03 05:51:45',
                    'updated_at' => '2021-03-03 05:51:45',
                ],
                [
                    'id' => 32,
                    'slug' => 'new-york',
                    'title' => 'New York',
                    'abbreviation' => 'NY',
                    'description' => null,
                    'capital' => 'Albany',
                    'country_id' => 1,
                    'created_at' => '2021-03-03 05:51:45',
                    'updated_at' => '2021-03-03 05:51:45',
                ],
                [
                    'id' => 33,
                    'slug' => 'north-carolina',
                    'title' => 'North Carolina',
                    'abbreviation' => 'NC',
                    'description' => null,
                    'capital' => 'Raleigh',
                    'country_id' => 1,
                    'created_at' => '2021-03-03 05:51:45',
                    'updated_at' => '2021-03-03 05:51:45',
                ],
                [
                    'id' => 34,
                    'slug' => 'north-dakota',
                    'title' => 'North Dakota',
                    'abbreviation' => 'ND',
                    'description' => null,
                    'capital' => 'Bismarck',
                    'country_id' => 1,
                    'created_at' => '2021-03-03 05:51:45',
                    'updated_at' => '2021-03-03 05:51:45',
                ],
                [
                    'id' => 35,
                    'slug' => 'ohio',
                    'title' => 'Ohio',
                    'abbreviation' => 'OH',
                    'description' => null,
                    'capital' => 'Columbus',
                    'country_id' => 1,
                    'created_at' => '2021-03-03 05:51:45',
                    'updated_at' => '2021-03-03 05:51:45',
                ],
                [
                    'id' => 36,
                    'slug' => 'oklahoma',
                    'title' => 'Oklahoma',
                    'abbreviation' => 'OK',
                    'description' => null,
                    'capital' => 'Oklahoma City',
                    'country_id' => 1,
                    'created_at' => '2021-03-03 05:51:45',
                    'updated_at' => '2021-03-03 05:51:45',
                ],
                [
                    'id' => 37,
                    'slug' => 'oregon',
                    'title' => 'Oregon',
                    'abbreviation' => 'OR',
                    'description' => null,
                    'capital' => 'Salem',
                    'country_id' => 1,
                    'created_at' => '2021-03-03 05:51:45',
                    'updated_at' => '2021-03-03 05:51:45',
                ],
                [
                    'id' => 38,
                    'slug' => 'pennsylvania',
                    'title' => 'Pennsylvania',
                    'abbreviation' => 'PA',
                    'description' => null,
                    'capital' => 'Harrisburg',
                    'country_id' => 1,
                    'created_at' => '2021-03-03 05:51:45',
                    'updated_at' => '2021-03-03 05:51:45',
                ],
                [
                    'id' => 39,
                    'slug' => 'rhode-island',
                    'title' => 'Rhode Island',
                    'abbreviation' => 'RI',
                    'description' => null,
                    'capital' => 'Providence',
                    'country_id' => 1,
                    'created_at' => '2021-03-03 05:51:45',
                    'updated_at' => '2021-03-03 05:51:45',
                ],
                [
                    'id' => 40,
                    'slug' => 'south-carolina',
                    'title' => 'South Carolina',
                    'abbreviation' => 'SC',
                    'description' => null,
                    'capital' => 'Columbia',
                    'country_id' => 1,
                    'created_at' => '2021-03-03 05:51:45',
                    'updated_at' => '2021-03-03 05:51:45',
                ],
                [
                    'id' => 41,
                    'slug' => 'south-dakota',
                    'title' => 'South Dakota',
                    'abbreviation' => 'SD',
                    'description' => null,
                    'capital' => 'Pierre',
                    'country_id' => 1,
                    'created_at' => '2021-03-03 05:51:45',
                    'updated_at' => '2021-03-03 05:51:45',
                ],
                [
                    'id' => 42,
                    'slug' => 'tennessee',
                    'title' => 'Tennessee',
                    'abbreviation' => 'TN',
                    'description' => null,
                    'capital' => 'Nashville',
                    'country_id' => 1,
                    'created_at' => '2021-03-03 05:51:45',
                    'updated_at' => '2021-03-03 05:51:45',
                ],
                [
                    'id' => 43,
                    'slug' => 'texas',
                    'title' => 'Texas',
                    'abbreviation' => 'TX',
                    'description' => null,
                    'capital' => 'Austin',
                    'country_id' => 1,
                    'created_at' => '2021-03-03 05:51:45',
                    'updated_at' => '2021-03-03 05:51:45',
                ],
                [
                    'id' => 44,
                    'slug' => 'utah',
                    'title' => 'Utah',
                    'abbreviation' => 'UT',
                    'description' => null,
                    'capital' => 'Salt Lake City',
                    'country_id' => 1,
                    'created_at' => '2021-03-03 05:51:45',
                    'updated_at' => '2021-03-03 05:51:45',
                ],
                [
                    'id' => 45,
                    'slug' => 'vermont',
                    'title' => 'Vermont',
                    'abbreviation' => 'VT',
                    'description' => null,
                    'capital' => 'Montpelier',
                    'country_id' => 1,
                    'created_at' => '2021-03-03 05:51:45',
                    'updated_at' => '2021-03-03 05:51:45',
                ],
                [
                    'id' => 46,
                    'slug' => 'virginia',
                    'title' => 'Virginia',
                    'abbreviation' => 'VA',
                    'description' => null,
                    'capital' => 'Richmond',
                    'country_id' => 1,
                    'created_at' => '2021-03-03 05:51:45',
                    'updated_at' => '2021-03-03 05:51:45',
                ],
                [
                    'id' => 47,
                    'slug' => 'washington',
                    'title' => 'Washington',
                    'abbreviation' => 'WA',
                    'description' => null,
                    'capital' => 'Olympia',
                    'country_id' => 1,
                    'created_at' => '2021-03-03 05:51:45',
                    'updated_at' => '2021-03-03 05:51:45',
                ],
                [
                    'id' => 48,
                    'slug' => 'west-virginia',
                    'title' => 'West Virginia',
                    'abbreviation' => 'WV',
                    'description' => null,
                    'capital' => 'Charleston',
                    'country_id' => 1,
                    'created_at' => '2021-03-03 05:51:45',
                    'updated_at' => '2021-03-03 05:51:45',
                ],
                [
                    'id' => 49,
                    'slug' => 'wisconsin',
                    'title' => 'Wisconsin',
                    'abbreviation' => 'WI',
                    'description' => null,
                    'capital' => 'Madison',
                    'country_id' => 1,
                    'created_at' => '2021-03-03 05:51:45',
                    'updated_at' => '2021-03-03 05:51:45',
                ],
                [
                    'id' => 50,
                    'slug' => 'wyoming',
                    'title' => 'Wyoming',
                    'abbreviation' => 'WY',
                    'description' => null,
                    'capital' => 'Cheyenne',
                    'country_id' => 1,
                    'created_at' => '2021-03-03 05:51:45',
                    'updated_at' => '2021-03-03 05:51:45',
                ],
                [
                    'id' => 51,
                    'slug' => 'dc',
                    'title' => 'District of Columbia',
                    'abbreviation' => 'DC',
                    'description' => null,
                    'capital' => 'Washington',
                    'country_id' => 1,
                    'created_at' => '2021-03-03 05:51:45',
                    'updated_at' => '2021-03-03 05:51:45',
                ],
                [
                    'id' => 52,
                    'slug' => 'puerto-rico',
                    'title' => 'Puerto Rico',
                    'abbreviation' => 'PR',
                    'description' => null,
                    'capital' => 'San Juan',
                    'country_id' => 1,
                    'created_at' => '2021-03-03 05:51:45',
                    'updated_at' => '2021-03-03 05:51:45',
                ],
                [
                    'id' => 53,
                    'slug' => 'virgin-islands',
                    'title' => 'Virgin Islands',
                    'abbreviation' => 'VI',
                    'description' => null,
                    'capital' => null,
                    'country_id' => 1,
                    'created_at' => '2021-03-03 05:51:45',
                    'updated_at' => '2021-03-03 05:51:45',
                ],
                [
                    'id' => 54,
                    'slug' => 'guam',
                    'title' => 'Guam',
                    'abbreviation' => 'GU',
                    'description' => null,
                    'capital' => null,
                    'country_id' => 1,
                    'created_at' => '2021-03-03 05:51:45',
                    'updated_at' => '2021-03-03 05:51:45',
                ],
                [
                    'id' => 55,
                    'slug' => 'us-armed-forces-americas',
                    'title' => 'US Armed Forces – Americas',
                    'abbreviation' => 'AA',
                    'description' => null,
                    'capital' => null,
                    'country_id' => 1,
                    'created_at' => '2021-03-03 05:51:45',
                    'updated_at' => '2021-03-03 05:51:45',
                ],
                [
                    'id' => 56,
                    'slug' => 'us-armed-forces-europe',
                    'title' => 'US Armed Forces – Europe',
                    'abbreviation' => 'AE',
                    'description' => null,
                    'capital' => null,
                    'country_id' => 1,
                    'created_at' => '2021-03-03 05:51:45',
                    'updated_at' => '2021-03-03 05:51:45',
                ],
                [
                    'id' => 57,
                    'slug' => 'us-armed-forces-pacific',
                    'title' => 'US Armed Forces – Pacific',
                    'abbreviation' => 'AP',
                    'description' => null,
                    'capital' => null,
                    'country_id' => 1,
                    'created_at' => '2021-03-03 05:51:45',
                    'updated_at' => '2021-03-03 05:51:45',
                ],
                [
                    'id' => 58,
                    'slug' => 'samoa',
                    'title' => 'American Samoa',
                    'abbreviation' => 'AS',
                    'description' => null,
                    'capital' => null,
                    'country_id' => 1,
                    'created_at' => '2021-03-03 05:51:45',
                    'updated_at' => '2021-03-03 05:51:45',
                ],
                [
                    'id' => 59,
                    'slug' => 'mariana-islands',
                    'title' => 'Mariana Islands',
                    'abbreviation' => 'MP',
                    'description' => null,
                    'capital' => null,
                    'country_id' => 1,
                    'created_at' => '2021-03-03 05:51:45',
                    'updated_at' => '2021-03-03 05:51:45',
                ]
            ] as $state) {
                State::firstOrCreate($state);
            }
        }
    }
}
