<?php

declare(strict_types=1);

use Carbon\Carbon;
use Illuminate\Database\Migrations\Migration;
use Tipoff\Addresses\Models\Country;
use Tipoff\Addresses\Models\CountryCallingcode;

class AddWorldCallingcode extends Migration
{
    public function up()
    {
        $callingcodeData = [
            [
                'country_id' => Country::fromAbbreviation('ABW')->getId(),
                'code' => '297',
                'display' => '+2 97',
                'root' => '+2',
                'suffix' => '97',
            ],
            [
                'country_id' => Country::fromAbbreviation('AFG')->getId(),
                'code' => '93',
                'display' => '+9 3',
                'root' => '+9',
                'suffix' => '3',
            ],
            [
                'country_id' => Country::fromAbbreviation('AGO')->getId(),
                'code' => '244',
                'display' => '+2 44',
                'root' => '+2',
                'suffix' => '44',
            ],
            [
                'country_id' => Country::fromAbbreviation('AIA')->getId(),
                'code' => '1264',
                'display' => '+1 264',
                'root' => '+1',
                'suffix' => '264',
            ],
            [
                'country_id' => Country::fromAbbreviation('ALA')->getId(),
                'code' => '35818',
                'display' => '+3 5818',
                'root' => '+3',
                'suffix' => '5818',
            ],
            [
                'country_id' => Country::fromAbbreviation('ALB')->getId(),
                'code' => '355',
                'display' => '+3 55',
                'root' => '+3',
                'suffix' => '55',
            ],
            [
                'country_id' => Country::fromAbbreviation('AND')->getId(),
                'code' => '376',
                'display' => '+3 76',
                'root' => '+3',
                'suffix' => '76',
            ],
            [
                'country_id' => Country::fromAbbreviation('ARE')->getId(),
                'code' => '971',
                'display' => '+9 71',
                'root' => '+9',
                'suffix' => '71',
            ],
            [
                'country_id' => Country::fromAbbreviation('ARG')->getId(),
                'code' => '54',
                'display' => '+5 4',
                'root' => '+5',
                'suffix' => '4',
            ],
            [
                'country_id' => Country::fromAbbreviation('ARM')->getId(),
                'code' => '374',
                'display' => '+3 74',
                'root' => '+3',
                'suffix' => '74',
            ],
            [
                'country_id' => Country::fromAbbreviation('ASM')->getId(),
                'code' => '1684',
                'display' => '+1 684',
                'root' => '+1',
                'suffix' => '684',
            ],
            [
                'country_id' => Country::fromAbbreviation('ATF')->getId(),
                'code' => '262',
                'display' => '+2 62',
                'root' => '+2',
                'suffix' => '62',
            ],
            [
                'country_id' => Country::fromAbbreviation('ATG')->getId(),
                'code' => '1268',
                'display' => '+1 268',
                'root' => '+1',
                'suffix' => '268',
            ],
            [
                'country_id' => Country::fromAbbreviation('AUS')->getId(),
                'code' => '61',
                'display' => '+6 1',
                'root' => '+6',
                'suffix' => '1',
            ],
            [
                'country_id' => Country::fromAbbreviation('AUT')->getId(),
                'code' => '43',
                'display' => '+4 3',
                'root' => '+4',
                'suffix' => '3',
            ],
            [
                'country_id' => Country::fromAbbreviation('AZE')->getId(),
                'code' => '994',
                'display' => '+9 94',
                'root' => '+9',
                'suffix' => '94',
            ],
            [
                'country_id' => Country::fromAbbreviation('BDI')->getId(),
                'code' => '257',
                'display' => '+2 57',
                'root' => '+2',
                'suffix' => '57',
            ],
            [
                'country_id' => Country::fromAbbreviation('BEL')->getId(),
                'code' => '32',
                'display' => '+3 2',
                'root' => '+3',
                'suffix' => '2',
            ],
            [
                'country_id' => Country::fromAbbreviation('BEN')->getId(),
                'code' => '229',
                'display' => '+2 29',
                'root' => '+2',
                'suffix' => '29',
            ],
            [
                'country_id' => Country::fromAbbreviation('BFA')->getId(),
                'code' => '226',
                'display' => '+2 26',
                'root' => '+2',
                'suffix' => '26',
            ],
            [
                'country_id' => Country::fromAbbreviation('BGD')->getId(),
                'code' => '880',
                'display' => '+8 80',
                'root' => '+8',
                'suffix' => '80',
            ],
            [
                'country_id' => Country::fromAbbreviation('BGR')->getId(),
                'code' => '359',
                'display' => '+3 59',
                'root' => '+3',
                'suffix' => '59',
            ],
            [
                'country_id' => Country::fromAbbreviation('BHR')->getId(),
                'code' => '973',
                'display' => '+9 73',
                'root' => '+9',
                'suffix' => '73',
            ],
            [
                'country_id' => Country::fromAbbreviation('BHS')->getId(),
                'code' => '1242',
                'display' => '+1 242',
                'root' => '+1',
                'suffix' => '242',
            ],
            [
                'country_id' => Country::fromAbbreviation('BIH')->getId(),
                'code' => '387',
                'display' => '+3 87',
                'root' => '+3',
                'suffix' => '87',
            ],
            [
                'country_id' => Country::fromAbbreviation('BLM')->getId(),
                'code' => '590',
                'display' => '+5 90',
                'root' => '+5',
                'suffix' => '90',
            ],
            [
                'country_id' => Country::fromAbbreviation('SHN')->getId(),
                'code' => '290',
                'display' => '+2 90',
                'root' => '+2',
                'suffix' => '90',
            ],
            [
                'country_id' => Country::fromAbbreviation('BLR')->getId(),
                'code' => '375',
                'display' => '+3 75',
                'root' => '+3',
                'suffix' => '75',
            ],
            [
                'country_id' => Country::fromAbbreviation('BLZ')->getId(),
                'code' => '501',
                'display' => '+5 01',
                'root' => '+5',
                'suffix' => '01',
            ],
            [
                'country_id' => Country::fromAbbreviation('BMU')->getId(),
                'code' => '1441',
                'display' => '+1 441',
                'root' => '+1',
                'suffix' => '441',
            ],
            [
                'country_id' => Country::fromAbbreviation('BOL')->getId(),
                'code' => '591',
                'display' => '+5 91',
                'root' => '+5',
                'suffix' => '91',
            ],
            [
                'country_id' => Country::fromAbbreviation('BES')->getId(),
                'code' => '599',
                'display' => '+5 99',
                'root' => '+5',
                'suffix' => '99',
            ],
            [
                'country_id' => Country::fromAbbreviation('BRA')->getId(),
                'code' => '55',
                'display' => '+5 5',
                'root' => '+5',
                'suffix' => '5',
            ],
            [
                'country_id' => Country::fromAbbreviation('BRB')->getId(),
                'code' => '1246',
                'display' => '+1 246',
                'root' => '+1',
                'suffix' => '246',
            ],
            [
                'country_id' => Country::fromAbbreviation('BRN')->getId(),
                'code' => '673',
                'display' => '+6 73',
                'root' => '+6',
                'suffix' => '73',
            ],
            [
                'country_id' => Country::fromAbbreviation('BTN')->getId(),
                'code' => '975',
                'display' => '+9 75',
                'root' => '+9',
                'suffix' => '75',
            ],
            [
                'country_id' => Country::fromAbbreviation('BVT')->getId(),
                'code' => '47',
                'display' => '+4 7',
                'root' => '+4',
                'suffix' => '7',
            ],
            [
                'country_id' => Country::fromAbbreviation('BWA')->getId(),
                'code' => '267',
                'display' => '+2 67',
                'root' => '+2',
                'suffix' => '67',
            ],
            [
                'country_id' => Country::fromAbbreviation('CAF')->getId(),
                'code' => '236',
                'display' => '+2 36',
                'root' => '+2',
                'suffix' => '36',
            ],
            [
                'country_id' => Country::fromAbbreviation('CAN')->getId(),
                'code' => '1',
                'display' => '+1 ',
                'root' => '+1',
                'suffix' => '',
            ],
            [
                'country_id' => Country::fromAbbreviation('CCK')->getId(),
                'code' => '61',
                'display' => '+6 1',
                'root' => '+6',
                'suffix' => '1',
            ],
            [
                'country_id' => Country::fromAbbreviation('CHE')->getId(),
                'code' => '41',
                'display' => '+4 1',
                'root' => '+4',
                'suffix' => '1',
            ],
            [
                'country_id' => Country::fromAbbreviation('CHL')->getId(),
                'code' => '56',
                'display' => '+5 6',
                'root' => '+5',
                'suffix' => '6',
            ],
            [
                'country_id' => Country::fromAbbreviation('CHN')->getId(),
                'code' => '86',
                'display' => '+8 6',
                'root' => '+8',
                'suffix' => '6',
            ],
            [
                'country_id' => Country::fromAbbreviation('CIV')->getId(),
                'code' => '225',
                'display' => '+2 25',
                'root' => '+2',
                'suffix' => '25',
            ],
            [
                'country_id' => Country::fromAbbreviation('CMR')->getId(),
                'code' => '237',
                'display' => '+2 37',
                'root' => '+2',
                'suffix' => '37',
            ],
            [
                'country_id' => Country::fromAbbreviation('COD')->getId(),
                'code' => '243',
                'display' => '+2 43',
                'root' => '+2',
                'suffix' => '43',
            ],
            [
                'country_id' => Country::fromAbbreviation('COG')->getId(),
                'code' => '242',
                'display' => '+2 42',
                'root' => '+2',
                'suffix' => '42',
            ],
            [
                'country_id' => Country::fromAbbreviation('COK')->getId(),
                'code' => '682',
                'display' => '+6 82',
                'root' => '+6',
                'suffix' => '82',
            ],
            [
                'country_id' => Country::fromAbbreviation('COL')->getId(),
                'code' => '57',
                'display' => '+5 7',
                'root' => '+5',
                'suffix' => '7',
            ],
            [
                'country_id' => Country::fromAbbreviation('COM')->getId(),
                'code' => '269',
                'display' => '+2 69',
                'root' => '+2',
                'suffix' => '69',
            ],
            [
                'country_id' => Country::fromAbbreviation('CPV')->getId(),
                'code' => '238',
                'display' => '+2 38',
                'root' => '+2',
                'suffix' => '38',
            ],
            [
                'country_id' => Country::fromAbbreviation('CRI')->getId(),
                'code' => '506',
                'display' => '+5 06',
                'root' => '+5',
                'suffix' => '06',
            ],
            [
                'country_id' => Country::fromAbbreviation('CUB')->getId(),
                'code' => '53',
                'display' => '+5 3',
                'root' => '+5',
                'suffix' => '3',
            ],
            [
                'country_id' => Country::fromAbbreviation('CUW')->getId(),
                'code' => '599',
                'display' => '+5 99',
                'root' => '+5',
                'suffix' => '99',
            ],
            [
                'country_id' => Country::fromAbbreviation('CXR')->getId(),
                'code' => '61',
                'display' => '+6 1',
                'root' => '+6',
                'suffix' => '1',
            ],
            [
                'country_id' => Country::fromAbbreviation('CYM')->getId(),
                'code' => '1345',
                'display' => '+1 345',
                'root' => '+1',
                'suffix' => '345',
            ],
            [
                'country_id' => Country::fromAbbreviation('CYP')->getId(),
                'code' => '357',
                'display' => '+3 57',
                'root' => '+3',
                'suffix' => '57',
            ],
            [
                'country_id' => Country::fromAbbreviation('CZE')->getId(),
                'code' => '420',
                'display' => '+4 20',
                'root' => '+4',
                'suffix' => '20',
            ],
            [
                'country_id' => Country::fromAbbreviation('DEU')->getId(),
                'code' => '49',
                'display' => '+4 9',
                'root' => '+4',
                'suffix' => '9',
            ],
            [
                'country_id' => Country::fromAbbreviation('DJI')->getId(),
                'code' => '253',
                'display' => '+2 53',
                'root' => '+2',
                'suffix' => '53',
            ],
            [
                'country_id' => Country::fromAbbreviation('DMA')->getId(),
                'code' => '1767',
                'display' => '+1 767',
                'root' => '+1',
                'suffix' => '767',
            ],
            [
                'country_id' => Country::fromAbbreviation('DNK')->getId(),
                'code' => '45',
                'display' => '+4 5',
                'root' => '+4',
                'suffix' => '5',
            ],
            [
                'country_id' => Country::fromAbbreviation('DOM')->getId(),
                'code' => '1809',
                'display' => '+1 809',
                'root' => '+1',
                'suffix' => '809',
            ],
            [
                'country_id' => Country::fromAbbreviation('DZA')->getId(),
                'code' => '213',
                'display' => '+2 13',
                'root' => '+2',
                'suffix' => '13',
            ],
            [
                'country_id' => Country::fromAbbreviation('ECU')->getId(),
                'code' => '593',
                'display' => '+5 93',
                'root' => '+5',
                'suffix' => '93',
            ],
            [
                'country_id' => Country::fromAbbreviation('EGY')->getId(),
                'code' => '20',
                'display' => '+2 0',
                'root' => '+2',
                'suffix' => '0',
            ],
            [
                'country_id' => Country::fromAbbreviation('ERI')->getId(),
                'code' => '291',
                'display' => '+2 91',
                'root' => '+2',
                'suffix' => '91',
            ],
            [
                'country_id' => Country::fromAbbreviation('ESH')->getId(),
                'code' => '2125288',
                'display' => '+2 125288',
                'root' => '+2',
                'suffix' => '125288',
            ],
            [
                'country_id' => Country::fromAbbreviation('ESP')->getId(),
                'code' => '34',
                'display' => '+3 4',
                'root' => '+3',
                'suffix' => '4',
            ],
            [
                'country_id' => Country::fromAbbreviation('EST')->getId(),
                'code' => '372',
                'display' => '+3 72',
                'root' => '+3',
                'suffix' => '72',
            ],
            [
                'country_id' => Country::fromAbbreviation('ETH')->getId(),
                'code' => '251',
                'display' => '+2 51',
                'root' => '+2',
                'suffix' => '51',
            ],
            [
                'country_id' => Country::fromAbbreviation('FIN')->getId(),
                'code' => '358',
                'display' => '+3 58',
                'root' => '+3',
                'suffix' => '58',
            ],
            [
                'country_id' => Country::fromAbbreviation('FJI')->getId(),
                'code' => '679',
                'display' => '+6 79',
                'root' => '+6',
                'suffix' => '79',
            ],
            [
                'country_id' => Country::fromAbbreviation('FLK')->getId(),
                'code' => '500',
                'display' => '+5 00',
                'root' => '+5',
                'suffix' => '00',
            ],
            [
                'country_id' => Country::fromAbbreviation('FRA')->getId(),
                'code' => '33',
                'display' => '+3 3',
                'root' => '+3',
                'suffix' => '3',
            ],
            [
                'country_id' => Country::fromAbbreviation('FRO')->getId(),
                'code' => '298',
                'display' => '+2 98',
                'root' => '+2',
                'suffix' => '98',
            ],
            [
                'country_id' => Country::fromAbbreviation('FSM')->getId(),
                'code' => '691',
                'display' => '+6 91',
                'root' => '+6',
                'suffix' => '91',
            ],
            [
                'country_id' => Country::fromAbbreviation('GAB')->getId(),
                'code' => '241',
                'display' => '+2 41',
                'root' => '+2',
                'suffix' => '41',
            ],
            [
                'country_id' => Country::fromAbbreviation('GBR')->getId(),
                'code' => '44',
                'display' => '+4 4',
                'root' => '+4',
                'suffix' => '4',
            ],
            [
                'country_id' => Country::fromAbbreviation('GEO')->getId(),
                'code' => '995',
                'display' => '+9 95',
                'root' => '+9',
                'suffix' => '95',
            ],
            [
                'country_id' => Country::fromAbbreviation('GGY')->getId(),
                'code' => '44',
                'display' => '+4 4',
                'root' => '+4',
                'suffix' => '4',
            ],
            [
                'country_id' => Country::fromAbbreviation('GHA')->getId(),
                'code' => '233',
                'display' => '+2 33',
                'root' => '+2',
                'suffix' => '33',
            ],
            [
                'country_id' => Country::fromAbbreviation('GIB')->getId(),
                'code' => '350',
                'display' => '+3 50',
                'root' => '+3',
                'suffix' => '50',
            ],
            [
                'country_id' => Country::fromAbbreviation('GIN')->getId(),
                'code' => '224',
                'display' => '+2 24',
                'root' => '+2',
                'suffix' => '24',
            ],
            [
                'country_id' => Country::fromAbbreviation('GLP')->getId(),
                'code' => '590',
                'display' => '+5 90',
                'root' => '+5',
                'suffix' => '90',
            ],
            [
                'country_id' => Country::fromAbbreviation('GMB')->getId(),
                'code' => '220',
                'display' => '+2 20',
                'root' => '+2',
                'suffix' => '20',
            ],
            [
                'country_id' => Country::fromAbbreviation('GNB')->getId(),
                'code' => '245',
                'display' => '+2 45',
                'root' => '+2',
                'suffix' => '45',
            ],
            [
                'country_id' => Country::fromAbbreviation('GNQ')->getId(),
                'code' => '240',
                'display' => '+2 40',
                'root' => '+2',
                'suffix' => '40',
            ],
            [
                'country_id' => Country::fromAbbreviation('GRC')->getId(),
                'code' => '30',
                'display' => '+3 0',
                'root' => '+3',
                'suffix' => '0',
            ],
            [
                'country_id' => Country::fromAbbreviation('GRD')->getId(),
                'code' => '1473',
                'display' => '+1 473',
                'root' => '+1',
                'suffix' => '473',
            ],
            [
                'country_id' => Country::fromAbbreviation('GRL')->getId(),
                'code' => '299',
                'display' => '+2 99',
                'root' => '+2',
                'suffix' => '99',
            ],
            [
                'country_id' => Country::fromAbbreviation('GTM')->getId(),
                'code' => '502',
                'display' => '+5 02',
                'root' => '+5',
                'suffix' => '02',
            ],
            [
                'country_id' => Country::fromAbbreviation('GUF')->getId(),
                'code' => '594',
                'display' => '+5 94',
                'root' => '+5',
                'suffix' => '94',
            ],
            [
                'country_id' => Country::fromAbbreviation('GUM')->getId(),
                'code' => '1671',
                'display' => '+1 671',
                'root' => '+1',
                'suffix' => '671',
            ],
            [
                'country_id' => Country::fromAbbreviation('GUY')->getId(),
                'code' => '592',
                'display' => '+5 92',
                'root' => '+5',
                'suffix' => '92',
            ],
            [
                'country_id' => Country::fromAbbreviation('HKG')->getId(),
                'code' => '852',
                'display' => '+8 52',
                'root' => '+8',
                'suffix' => '52',
            ],
            [
                'country_id' => Country::fromAbbreviation('HND')->getId(),
                'code' => '504',
                'display' => '+5 04',
                'root' => '+5',
                'suffix' => '04',
            ],
            [
                'country_id' => Country::fromAbbreviation('HRV')->getId(),
                'code' => '385',
                'display' => '+3 85',
                'root' => '+3',
                'suffix' => '85',
            ],
            [
                'country_id' => Country::fromAbbreviation('HTI')->getId(),
                'code' => '509',
                'display' => '+5 09',
                'root' => '+5',
                'suffix' => '09',
            ],
            [
                'country_id' => Country::fromAbbreviation('HUN')->getId(),
                'code' => '36',
                'display' => '+3 6',
                'root' => '+3',
                'suffix' => '6',
            ],
            [
                'country_id' => Country::fromAbbreviation('IDN')->getId(),
                'code' => '62',
                'display' => '+6 2',
                'root' => '+6',
                'suffix' => '2',
            ],
            [
                'country_id' => Country::fromAbbreviation('IMN')->getId(),
                'code' => '44',
                'display' => '+4 4',
                'root' => '+4',
                'suffix' => '4',
            ],
            [
                'country_id' => Country::fromAbbreviation('IND')->getId(),
                'code' => '91',
                'display' => '+9 1',
                'root' => '+9',
                'suffix' => '1',
            ],
            [
                'country_id' => Country::fromAbbreviation('IOT')->getId(),
                'code' => '246',
                'display' => '+2 46',
                'root' => '+2',
                'suffix' => '46',
            ],
            [
                'country_id' => Country::fromAbbreviation('IRL')->getId(),
                'code' => '353',
                'display' => '+3 53',
                'root' => '+3',
                'suffix' => '53',
            ],
            [
                'country_id' => Country::fromAbbreviation('IRN')->getId(),
                'code' => '98',
                'display' => '+9 8',
                'root' => '+9',
                'suffix' => '8',
            ],
            [
                'country_id' => Country::fromAbbreviation('IRQ')->getId(),
                'code' => '964',
                'display' => '+9 64',
                'root' => '+9',
                'suffix' => '64',
            ],
            [
                'country_id' => Country::fromAbbreviation('ISL')->getId(),
                'code' => '354',
                'display' => '+3 54',
                'root' => '+3',
                'suffix' => '54',
            ],
            [
                'country_id' => Country::fromAbbreviation('ISR')->getId(),
                'code' => '972',
                'display' => '+9 72',
                'root' => '+9',
                'suffix' => '72',
            ],
            [
                'country_id' => Country::fromAbbreviation('ITA')->getId(),
                'code' => '39',
                'display' => '+3 9',
                'root' => '+3',
                'suffix' => '9',
            ],
            [
                'country_id' => Country::fromAbbreviation('JAM')->getId(),
                'code' => '1876',
                'display' => '+1 876',
                'root' => '+1',
                'suffix' => '876',
            ],
            [
                'country_id' => Country::fromAbbreviation('JEY')->getId(),
                'code' => '44',
                'display' => '+4 4',
                'root' => '+4',
                'suffix' => '4',
            ],
            [
                'country_id' => Country::fromAbbreviation('JOR')->getId(),
                'code' => '962',
                'display' => '+9 62',
                'root' => '+9',
                'suffix' => '62',
            ],
            [
                'country_id' => Country::fromAbbreviation('JPN')->getId(),
                'code' => '81',
                'display' => '+8 1',
                'root' => '+8',
                'suffix' => '1',
            ],
            [
                'country_id' => Country::fromAbbreviation('KAZ')->getId(),
                'code' => '76XX',
                'display' => '+7 6XX',
                'root' => '+7',
                'suffix' => '6XX',
            ],
            [
                'country_id' => Country::fromAbbreviation('KEN')->getId(),
                'code' => '254',
                'display' => '+2 54',
                'root' => '+2',
                'suffix' => '54',
            ],
            [
                'country_id' => Country::fromAbbreviation('KGZ')->getId(),
                'code' => '996',
                'display' => '+9 96',
                'root' => '+9',
                'suffix' => '96',
            ],
            [
                'country_id' => Country::fromAbbreviation('KHM')->getId(),
                'code' => '855',
                'display' => '+8 55',
                'root' => '+8',
                'suffix' => '55',
            ],
            [
                'country_id' => Country::fromAbbreviation('KIR')->getId(),
                'code' => '686',
                'display' => '+6 86',
                'root' => '+6',
                'suffix' => '86',
            ],
            [
                'country_id' => Country::fromAbbreviation('KNA')->getId(),
                'code' => '1869',
                'display' => '+1 869',
                'root' => '+1',
                'suffix' => '869',
            ],
            [
                'country_id' => Country::fromAbbreviation('KOR')->getId(),
                'code' => '82',
                'display' => '+8 2',
                'root' => '+8',
                'suffix' => '2',
            ],
            [
                'country_id' => Country::fromAbbreviation('UNK')->getId(),
                'code' => '383',
                'display' => '+3 83',
                'root' => '+3',
                'suffix' => '83',
            ],
            [
                'country_id' => Country::fromAbbreviation('KWT')->getId(),
                'code' => '965',
                'display' => '+9 65',
                'root' => '+9',
                'suffix' => '65',
            ],
            [
                'country_id' => Country::fromAbbreviation('LAO')->getId(),
                'code' => '856',
                'display' => '+8 56',
                'root' => '+8',
                'suffix' => '56',
            ],
            [
                'country_id' => Country::fromAbbreviation('LBN')->getId(),
                'code' => '961',
                'display' => '+9 61',
                'root' => '+9',
                'suffix' => '61',
            ],
            [
                'country_id' => Country::fromAbbreviation('LBR')->getId(),
                'code' => '231',
                'display' => '+2 31',
                'root' => '+2',
                'suffix' => '31',
            ],
            [
                'country_id' => Country::fromAbbreviation('LBY')->getId(),
                'code' => '218',
                'display' => '+2 18',
                'root' => '+2',
                'suffix' => '18',
            ],
            [
                'country_id' => Country::fromAbbreviation('LCA')->getId(),
                'code' => '1758',
                'display' => '+1 758',
                'root' => '+1',
                'suffix' => '758',
            ],
            [
                'country_id' => Country::fromAbbreviation('LIE')->getId(),
                'code' => '423',
                'display' => '+4 23',
                'root' => '+4',
                'suffix' => '23',
            ],
            [
                'country_id' => Country::fromAbbreviation('LKA')->getId(),
                'code' => '94',
                'display' => '+9 4',
                'root' => '+9',
                'suffix' => '4',
            ],
            [
                'country_id' => Country::fromAbbreviation('LSO')->getId(),
                'code' => '266',
                'display' => '+2 66',
                'root' => '+2',
                'suffix' => '66',
            ],
            [
                'country_id' => Country::fromAbbreviation('LTU')->getId(),
                'code' => '370',
                'display' => '+3 70',
                'root' => '+3',
                'suffix' => '70',
            ],
            [
                'country_id' => Country::fromAbbreviation('LUX')->getId(),
                'code' => '352',
                'display' => '+3 52',
                'root' => '+3',
                'suffix' => '52',
            ],
            [
                'country_id' => Country::fromAbbreviation('LVA')->getId(),
                'code' => '371',
                'display' => '+3 71',
                'root' => '+3',
                'suffix' => '71',
            ],
            [
                'country_id' => Country::fromAbbreviation('MAC')->getId(),
                'code' => '853',
                'display' => '+8 53',
                'root' => '+8',
                'suffix' => '53',
            ],
            [
                'country_id' => Country::fromAbbreviation('MAF')->getId(),
                'code' => '590',
                'display' => '+5 90',
                'root' => '+5',
                'suffix' => '90',
            ],
            [
                'country_id' => Country::fromAbbreviation('MAR')->getId(),
                'code' => '212',
                'display' => '+2 12',
                'root' => '+2',
                'suffix' => '12',
            ],
            [
                'country_id' => Country::fromAbbreviation('MCO')->getId(),
                'code' => '377',
                'display' => '+3 77',
                'root' => '+3',
                'suffix' => '77',
            ],
            [
                'country_id' => Country::fromAbbreviation('MDA')->getId(),
                'code' => '373',
                'display' => '+3 73',
                'root' => '+3',
                'suffix' => '73',
            ],
            [
                'country_id' => Country::fromAbbreviation('MDG')->getId(),
                'code' => '261',
                'display' => '+2 61',
                'root' => '+2',
                'suffix' => '61',
            ],
            [
                'country_id' => Country::fromAbbreviation('MDV')->getId(),
                'code' => '960',
                'display' => '+9 60',
                'root' => '+9',
                'suffix' => '60',
            ],
            [
                'country_id' => Country::fromAbbreviation('MEX')->getId(),
                'code' => '52',
                'display' => '+5 2',
                'root' => '+5',
                'suffix' => '2',
            ],
            [
                'country_id' => Country::fromAbbreviation('MHL')->getId(),
                'code' => '692',
                'display' => '+6 92',
                'root' => '+6',
                'suffix' => '92',
            ],
            [
                'country_id' => Country::fromAbbreviation('MKD')->getId(),
                'code' => '389',
                'display' => '+3 89',
                'root' => '+3',
                'suffix' => '89',
            ],
            [
                'country_id' => Country::fromAbbreviation('MLI')->getId(),
                'code' => '223',
                'display' => '+2 23',
                'root' => '+2',
                'suffix' => '23',
            ],
            [
                'country_id' => Country::fromAbbreviation('MLT')->getId(),
                'code' => '356',
                'display' => '+3 56',
                'root' => '+3',
                'suffix' => '56',
            ],
            [
                'country_id' => Country::fromAbbreviation('MMR')->getId(),
                'code' => '95',
                'display' => '+9 5',
                'root' => '+9',
                'suffix' => '5',
            ],
            [
                'country_id' => Country::fromAbbreviation('MNE')->getId(),
                'code' => '382',
                'display' => '+3 82',
                'root' => '+3',
                'suffix' => '82',
            ],
            [
                'country_id' => Country::fromAbbreviation('MNG')->getId(),
                'code' => '976',
                'display' => '+9 76',
                'root' => '+9',
                'suffix' => '76',
            ],
            [
                'country_id' => Country::fromAbbreviation('MNP')->getId(),
                'code' => '1670',
                'display' => '+1 670',
                'root' => '+1',
                'suffix' => '670',
            ],
            [
                'country_id' => Country::fromAbbreviation('MOZ')->getId(),
                'code' => '258',
                'display' => '+2 58',
                'root' => '+2',
                'suffix' => '58',
            ],
            [
                'country_id' => Country::fromAbbreviation('MRT')->getId(),
                'code' => '222',
                'display' => '+2 22',
                'root' => '+2',
                'suffix' => '22',
            ],
            [
                'country_id' => Country::fromAbbreviation('MSR')->getId(),
                'code' => '1664',
                'display' => '+1 664',
                'root' => '+1',
                'suffix' => '664',
            ],
            [
                'country_id' => Country::fromAbbreviation('MTQ')->getId(),
                'code' => '596',
                'display' => '+5 96',
                'root' => '+5',
                'suffix' => '96',
            ],
            [
                'country_id' => Country::fromAbbreviation('MUS')->getId(),
                'code' => '230',
                'display' => '+2 30',
                'root' => '+2',
                'suffix' => '30',
            ],
            [
                'country_id' => Country::fromAbbreviation('MWI')->getId(),
                'code' => '265',
                'display' => '+2 65',
                'root' => '+2',
                'suffix' => '65',
            ],
            [
                'country_id' => Country::fromAbbreviation('MYS')->getId(),
                'code' => '60',
                'display' => '+6 0',
                'root' => '+6',
                'suffix' => '0',
            ],
            [
                'country_id' => Country::fromAbbreviation('MYT')->getId(),
                'code' => '262',
                'display' => '+2 62',
                'root' => '+2',
                'suffix' => '62',
            ],
            [
                'country_id' => Country::fromAbbreviation('NAM')->getId(),
                'code' => '264',
                'display' => '+2 64',
                'root' => '+2',
                'suffix' => '64',
            ],
            [
                'country_id' => Country::fromAbbreviation('NCL')->getId(),
                'code' => '687',
                'display' => '+6 87',
                'root' => '+6',
                'suffix' => '87',
            ],
            [
                'country_id' => Country::fromAbbreviation('NER')->getId(),
                'code' => '227',
                'display' => '+2 27',
                'root' => '+2',
                'suffix' => '27',
            ],
            [
                'country_id' => Country::fromAbbreviation('NFK')->getId(),
                'code' => '672',
                'display' => '+6 72',
                'root' => '+6',
                'suffix' => '72',
            ],
            [
                'country_id' => Country::fromAbbreviation('NGA')->getId(),
                'code' => '234',
                'display' => '+2 34',
                'root' => '+2',
                'suffix' => '34',
            ],
            [
                'country_id' => Country::fromAbbreviation('NIC')->getId(),
                'code' => '505',
                'display' => '+5 05',
                'root' => '+5',
                'suffix' => '05',
            ],
            [
                'country_id' => Country::fromAbbreviation('NIU')->getId(),
                'code' => '683',
                'display' => '+6 83',
                'root' => '+6',
                'suffix' => '83',
            ],
            [
                'country_id' => Country::fromAbbreviation('NLD')->getId(),
                'code' => '31',
                'display' => '+3 1',
                'root' => '+3',
                'suffix' => '1',
            ],
            [
                'country_id' => Country::fromAbbreviation('NOR')->getId(),
                'code' => '47',
                'display' => '+4 7',
                'root' => '+4',
                'suffix' => '7',
            ],
            [
                'country_id' => Country::fromAbbreviation('NPL')->getId(),
                'code' => '977',
                'display' => '+9 77',
                'root' => '+9',
                'suffix' => '77',
            ],
            [
                'country_id' => Country::fromAbbreviation('NRU')->getId(),
                'code' => '674',
                'display' => '+6 74',
                'root' => '+6',
                'suffix' => '74',
            ],
            [
                'country_id' => Country::fromAbbreviation('NZL')->getId(),
                'code' => '64',
                'display' => '+6 4',
                'root' => '+6',
                'suffix' => '4',
            ],
            [
                'country_id' => Country::fromAbbreviation('OMN')->getId(),
                'code' => '968',
                'display' => '+9 68',
                'root' => '+9',
                'suffix' => '68',
            ],
            [
                'country_id' => Country::fromAbbreviation('PAK')->getId(),
                'code' => '92',
                'display' => '+9 2',
                'root' => '+9',
                'suffix' => '2',
            ],
            [
                'country_id' => Country::fromAbbreviation('PAN')->getId(),
                'code' => '507',
                'display' => '+5 07',
                'root' => '+5',
                'suffix' => '07',
            ],
            [
                'country_id' => Country::fromAbbreviation('PCN')->getId(),
                'code' => '64',
                'display' => '+6 4',
                'root' => '+6',
                'suffix' => '4',
            ],
            [
                'country_id' => Country::fromAbbreviation('PER')->getId(),
                'code' => '51',
                'display' => '+5 1',
                'root' => '+5',
                'suffix' => '1',
            ],
            [
                'country_id' => Country::fromAbbreviation('PHL')->getId(),
                'code' => '63',
                'display' => '+6 3',
                'root' => '+6',
                'suffix' => '3',
            ],
            [
                'country_id' => Country::fromAbbreviation('PLW')->getId(),
                'code' => '680',
                'display' => '+6 80',
                'root' => '+6',
                'suffix' => '80',
            ],
            [
                'country_id' => Country::fromAbbreviation('PNG')->getId(),
                'code' => '675',
                'display' => '+6 75',
                'root' => '+6',
                'suffix' => '75',
            ],
            [
                'country_id' => Country::fromAbbreviation('POL')->getId(),
                'code' => '48',
                'display' => '+4 8',
                'root' => '+4',
                'suffix' => '8',
            ],
            [
                'country_id' => Country::fromAbbreviation('PRI')->getId(),
                'code' => '1787',
                'display' => '+1 787',
                'root' => '+1',
                'suffix' => '787',
            ],
            [
                'country_id' => Country::fromAbbreviation('PRK')->getId(),
                'code' => '850',
                'display' => '+8 50',
                'root' => '+8',
                'suffix' => '50',
            ],
            [
                'country_id' => Country::fromAbbreviation('PRT')->getId(),
                'code' => '351',
                'display' => '+3 51',
                'root' => '+3',
                'suffix' => '51',
            ],
            [
                'country_id' => Country::fromAbbreviation('PRY')->getId(),
                'code' => '595',
                'display' => '+5 95',
                'root' => '+5',
                'suffix' => '95',
            ],
            [
                'country_id' => Country::fromAbbreviation('PSE')->getId(),
                'code' => '970',
                'display' => '+9 70',
                'root' => '+9',
                'suffix' => '70',
            ],
            [
                'country_id' => Country::fromAbbreviation('PYF')->getId(),
                'code' => '689',
                'display' => '+6 89',
                'root' => '+6',
                'suffix' => '89',
            ],
            [
                'country_id' => Country::fromAbbreviation('QAT')->getId(),
                'code' => '974',
                'display' => '+9 74',
                'root' => '+9',
                'suffix' => '74',
            ],
            [
                'country_id' => Country::fromAbbreviation('REU')->getId(),
                'code' => '262',
                'display' => '+2 62',
                'root' => '+2',
                'suffix' => '62',
            ],
            [
                'country_id' => Country::fromAbbreviation('ROU')->getId(),
                'code' => '40',
                'display' => '+4 0',
                'root' => '+4',
                'suffix' => '0',
            ],
            [
                'country_id' => Country::fromAbbreviation('RUS')->getId(),
                'code' => '73XX',
                'display' => '+7 3XX',
                'root' => '+7',
                'suffix' => '3XX',
            ],
            [
                'country_id' => Country::fromAbbreviation('RWA')->getId(),
                'code' => '250',
                'display' => '+2 50',
                'root' => '+2',
                'suffix' => '50',
            ],
            [
                'country_id' => Country::fromAbbreviation('SAU')->getId(),
                'code' => '966',
                'display' => '+9 66',
                'root' => '+9',
                'suffix' => '66',
            ],
            [
                'country_id' => Country::fromAbbreviation('SDN')->getId(),
                'code' => '249',
                'display' => '+2 49',
                'root' => '+2',
                'suffix' => '49',
            ],
            [
                'country_id' => Country::fromAbbreviation('SEN')->getId(),
                'code' => '221',
                'display' => '+2 21',
                'root' => '+2',
                'suffix' => '21',
            ],
            [
                'country_id' => Country::fromAbbreviation('SGP')->getId(),
                'code' => '65',
                'display' => '+6 5',
                'root' => '+6',
                'suffix' => '5',
            ],
            [
                'country_id' => Country::fromAbbreviation('SGS')->getId(),
                'code' => '500',
                'display' => '+5 00',
                'root' => '+5',
                'suffix' => '00',
            ],
            [
                'country_id' => Country::fromAbbreviation('SJM')->getId(),
                'code' => '4779',
                'display' => '+4 779',
                'root' => '+4',
                'suffix' => '779',
            ],
            [
                'country_id' => Country::fromAbbreviation('SLB')->getId(),
                'code' => '677',
                'display' => '+6 77',
                'root' => '+6',
                'suffix' => '77',
            ],
            [
                'country_id' => Country::fromAbbreviation('SLE')->getId(),
                'code' => '232',
                'display' => '+2 32',
                'root' => '+2',
                'suffix' => '32',
            ],
            [
                'country_id' => Country::fromAbbreviation('SLV')->getId(),
                'code' => '503',
                'display' => '+5 03',
                'root' => '+5',
                'suffix' => '03',
            ],
            [
                'country_id' => Country::fromAbbreviation('SMR')->getId(),
                'code' => '378',
                'display' => '+3 78',
                'root' => '+3',
                'suffix' => '78',
            ],
            [
                'country_id' => Country::fromAbbreviation('SOM')->getId(),
                'code' => '252',
                'display' => '+2 52',
                'root' => '+2',
                'suffix' => '52',
            ],
            [
                'country_id' => Country::fromAbbreviation('SPM')->getId(),
                'code' => '508',
                'display' => '+5 08',
                'root' => '+5',
                'suffix' => '08',
            ],
            [
                'country_id' => Country::fromAbbreviation('SRB')->getId(),
                'code' => '381',
                'display' => '+3 81',
                'root' => '+3',
                'suffix' => '81',
            ],
            [
                'country_id' => Country::fromAbbreviation('SSD')->getId(),
                'code' => '211',
                'display' => '+2 11',
                'root' => '+2',
                'suffix' => '11',
            ],
            [
                'country_id' => Country::fromAbbreviation('STP')->getId(),
                'code' => '239',
                'display' => '+2 39',
                'root' => '+2',
                'suffix' => '39',
            ],
            [
                'country_id' => Country::fromAbbreviation('SUR')->getId(),
                'code' => '597',
                'display' => '+5 97',
                'root' => '+5',
                'suffix' => '97',
            ],
            [
                'country_id' => Country::fromAbbreviation('SVK')->getId(),
                'code' => '421',
                'display' => '+4 21',
                'root' => '+4',
                'suffix' => '21',
            ],
            [
                'country_id' => Country::fromAbbreviation('SVN')->getId(),
                'code' => '386',
                'display' => '+3 86',
                'root' => '+3',
                'suffix' => '86',
            ],
            [
                'country_id' => Country::fromAbbreviation('SWE')->getId(),
                'code' => '46',
                'display' => '+4 6',
                'root' => '+4',
                'suffix' => '6',
            ],
            [
                'country_id' => Country::fromAbbreviation('SWZ')->getId(),
                'code' => '268',
                'display' => '+2 68',
                'root' => '+2',
                'suffix' => '68',
            ],
            [
                'country_id' => Country::fromAbbreviation('SXM')->getId(),
                'code' => '1721',
                'display' => '+1 721',
                'root' => '+1',
                'suffix' => '721',
            ],
            [
                'country_id' => Country::fromAbbreviation('SYC')->getId(),
                'code' => '248',
                'display' => '+2 48',
                'root' => '+2',
                'suffix' => '48',
            ],
            [
                'country_id' => Country::fromAbbreviation('SYR')->getId(),
                'code' => '963',
                'display' => '+9 63',
                'root' => '+9',
                'suffix' => '63',
            ],
            [
                'country_id' => Country::fromAbbreviation('TCA')->getId(),
                'code' => '1649',
                'display' => '+1 649',
                'root' => '+1',
                'suffix' => '649',
            ],
            [
                'country_id' => Country::fromAbbreviation('TCD')->getId(),
                'code' => '235',
                'display' => '+2 35',
                'root' => '+2',
                'suffix' => '35',
            ],
            [
                'country_id' => Country::fromAbbreviation('TGO')->getId(),
                'code' => '228',
                'display' => '+2 28',
                'root' => '+2',
                'suffix' => '28',
            ],
            [
                'country_id' => Country::fromAbbreviation('THA')->getId(),
                'code' => '66',
                'display' => '+6 6',
                'root' => '+6',
                'suffix' => '6',
            ],
            [
                'country_id' => Country::fromAbbreviation('TJK')->getId(),
                'code' => '992',
                'display' => '+9 92',
                'root' => '+9',
                'suffix' => '92',
            ],
            [
                'country_id' => Country::fromAbbreviation('TKL')->getId(),
                'code' => '690',
                'display' => '+6 90',
                'root' => '+6',
                'suffix' => '90',
            ],
            [
                'country_id' => Country::fromAbbreviation('TKM')->getId(),
                'code' => '993',
                'display' => '+9 93',
                'root' => '+9',
                'suffix' => '93',
            ],
            [
                'country_id' => Country::fromAbbreviation('TLS')->getId(),
                'code' => '670',
                'display' => '+6 70',
                'root' => '+6',
                'suffix' => '70',
            ],
            [
                'country_id' => Country::fromAbbreviation('TON')->getId(),
                'code' => '676',
                'display' => '+6 76',
                'root' => '+6',
                'suffix' => '76',
            ],
            [
                'country_id' => Country::fromAbbreviation('TTO')->getId(),
                'code' => '1868',
                'display' => '+1 868',
                'root' => '+1',
                'suffix' => '868',
            ],
            [
                'country_id' => Country::fromAbbreviation('TUN')->getId(),
                'code' => '216',
                'display' => '+2 16',
                'root' => '+2',
                'suffix' => '16',
            ],
            [
                'country_id' => Country::fromAbbreviation('TUR')->getId(),
                'code' => '90',
                'display' => '+9 0',
                'root' => '+9',
                'suffix' => '0',
            ],
            [
                'country_id' => Country::fromAbbreviation('TUV')->getId(),
                'code' => '688',
                'display' => '+6 88',
                'root' => '+6',
                'suffix' => '88',
            ],
            [
                'country_id' => Country::fromAbbreviation('TWN')->getId(),
                'code' => '886',
                'display' => '+8 86',
                'root' => '+8',
                'suffix' => '86',
            ],
            [
                'country_id' => Country::fromAbbreviation('TZA')->getId(),
                'code' => '255',
                'display' => '+2 55',
                'root' => '+2',
                'suffix' => '55',
            ],
            [
                'country_id' => Country::fromAbbreviation('UGA')->getId(),
                'code' => '256',
                'display' => '+2 56',
                'root' => '+2',
                'suffix' => '56',
            ],
            [
                'country_id' => Country::fromAbbreviation('UKR')->getId(),
                'code' => '380',
                'display' => '+3 80',
                'root' => '+3',
                'suffix' => '80',
            ],
            [
                'country_id' => Country::fromAbbreviation('UMI')->getId(),
                'code' => '268',
                'display' => '+2 68',
                'root' => '+2',
                'suffix' => '68',
            ],
            [
                'country_id' => Country::fromAbbreviation('URY')->getId(),
                'code' => '598',
                'display' => '+5 98',
                'root' => '+5',
                'suffix' => '98',
            ],
            [
                'country_id' => Country::fromAbbreviation('UZB')->getId(),
                'code' => '998',
                'display' => '+9 98',
                'root' => '+9',
                'suffix' => '98',
            ],
            [
                'country_id' => Country::fromAbbreviation('VAT')->getId(),
                'code' => '3906698',
                'display' => '+3 906698',
                'root' => '+3',
                'suffix' => '906698',
            ],
            [
                'country_id' => Country::fromAbbreviation('VCT')->getId(),
                'code' => '1784',
                'display' => '+1 784',
                'root' => '+1',
                'suffix' => '784',
            ],
            [
                'country_id' => Country::fromAbbreviation('VEN')->getId(),
                'code' => '58',
                'display' => '+5 8',
                'root' => '+5',
                'suffix' => '8',
            ],
            [
                'country_id' => Country::fromAbbreviation('VGB')->getId(),
                'code' => '1284',
                'display' => '+1 284',
                'root' => '+1',
                'suffix' => '284',
            ],
            [
                'country_id' => Country::fromAbbreviation('VIR')->getId(),
                'code' => '1340',
                'display' => '+1 340',
                'root' => '+1',
                'suffix' => '340',
            ],
            [
                'country_id' => Country::fromAbbreviation('VNM')->getId(),
                'code' => '84',
                'display' => '+8 4',
                'root' => '+8',
                'suffix' => '4',
            ],
            [
                'country_id' => Country::fromAbbreviation('VUT')->getId(),
                'code' => '678',
                'display' => '+6 78',
                'root' => '+6',
                'suffix' => '78',
            ],
            [
                'country_id' => Country::fromAbbreviation('WLF')->getId(),
                'code' => '681',
                'display' => '+6 81',
                'root' => '+6',
                'suffix' => '81',
            ],
            [
                'country_id' => Country::fromAbbreviation('WSM')->getId(),
                'code' => '685',
                'display' => '+6 85',
                'root' => '+6',
                'suffix' => '85',
            ],
            [
                'country_id' => Country::fromAbbreviation('YEM')->getId(),
                'code' => '967',
                'display' => '+9 67',
                'root' => '+9',
                'suffix' => '67',
            ],
            [
                'country_id' => Country::fromAbbreviation('ZAF')->getId(),
                'code' => '27',
                'display' => '+2 7',
                'root' => '+2',
                'suffix' => '7',
            ],
            [
                'country_id' => Country::fromAbbreviation('ZMB')->getId(),
                'code' => '260',
                'display' => '+2 60',
                'root' => '+2',
                'suffix' => '60',
            ],
            [
                'country_id' => Country::fromAbbreviation('ZWE')->getId(),
                'code' => '263',
                'display' => '+2 63',
                'root' => '+2',
                'suffix' => '63',
            ],
        ];

        CountryCallingcode::query()->insertOrIgnore($callingcodeData);
    }
}
